config/routes.rb
ResumeGenerator::Application.routes.draw do


  resources :resumes
  resources :projects, :only => [] do
    get :autocomplete_technology_name, :on => :collection
  end

  root :to => redirect("/resumes")

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :resume

  validates :title, :presence => true
  validates :company, :presence => true
  validates :place, :presence => true
  validates :from_date, :presence => true

  validate :from_date_must_be_past
  validate :from_date_must_be_before_until_date


  acts_as_taggable_on :technologies


  def from_date_must_be_past
    errors.add(:from_date, "must be a past date") if self.from_date.present? && self.from_date > Date.today
  end

  def from_date_must_be_before_until_date
    return unless  self.from_date.present? && self.until_date.present? && self.until_date < self.from_date
    errors.add(:from_date, "must be before until_date")
    errors.add(:until_date, "must be after from date")
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :resume

  acts_as_taggable_on :technologies

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  has_many :projects, :dependent => :destroy
  accepts_nested_attributes_for :projects, :allow_destroy => true

  has_many :experiences, :dependent => :destroy
  accepts_nested_attributes_for :experiences, :allow_destroy => true

  validates :first_name, :presence => true
  validates :last_name, :presence => true
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  autocomplete :technology, :name, :class_name => 'ActsAsTaggableOn::Tag'

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  respond_to :html, :except => [:show]
  respond_to :pdf, :only => [:show]

  def index
    @resumes = Resume.all
    respond_with(@resumes)
  end

  def show
    @resume = Resume.find(params[:id])
    respond_with(@resume) do |format|
      format.pdf do
        render  :pdf              => "resume",
                :show_as_html     => params[:debug].present?
      end
    end
  end

  def new
    @resume = Resume.new
    respond_with(@resume)
  end

  def edit
    @resume = Resume.find(params[:id])
  end

  def create
    @resume = Resume.new(resume_params)
    @resume.save
    respond_with(@resume)
  end

  def update
    @resume = Resume.find(params[:id])
    @resume.update_attributes(resume_params)
    respond_with(@resume)
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    respond_with(@resume)
  end


  protected

  def resume_params
    params.require(:resume).permit(:first_name, :last_name, :intro, :projects_attributes, :experiences_attributes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  div class="alert alert-#{(name == :notice) ?"success" : "error"}"
    a.close data-dismiss="alert"
    div id="flash_#{name}"
      = msg if msg.is_a?(String)

app/views/layouts/_navigation.html.slim
= link_to "Resume Generator", root_path, :class => 'brand'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"
    meta content="width=(device-width,)initial-scale=1.0" name="viewport"
    title= content_for?(:title) ? yield(:title) : "Resume Generator"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  body
    header.navbar.navbar-fixed-top
      nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main role="main"
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
    footer

app/views/resumes/_experience_fields.html.slim
= field_set_tag "Experience Details" do
  = f.input :title
  = f.input :company
  = f.input :place
  = f.input :from_date, :start_year => Date.today.year - 50, :end_year => Date.today.year , :discard_day => true, :order => [:month, :year]
  = f.input :until_date, :start_year => Date.today.year - 50, :end_year => Date.today.year , :discard_day => true, :order => [:month, :year],  :include_blank => true
  = f.input :description
  = f.input :technology_list, :url => autocomplete_technology_name_projects_path, :as => :autocomplete, :input_html => {:"data-delimiter" => ', '}
  = f.link_to_remove "Remove this experience"

app/views/resumes/_form.html.slim
= simple_nested_form_for @resume do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :intro

  = f.fields_for :projects
  p
    = f.link_to_add "Add Project", :projects

  = f.fields_for :experiences
  p
    = f.link_to_add "Add Experience", :experiences

  = f.button :submit

app/views/resumes/_project_fields.html.slim
= field_set_tag "Project Details" do
  = f.input :title
  = f.input :description
  = f.input :duration
  = f.input :technology_list, :url => autocomplete_technology_name_projects_path, :as => :autocomplete, :input_html => {:"data-delimiter" => ', '}
  = f.link_to_remove "Remove this project"

app/views/resumes/edit.html.slim
h1 Editing resume

== render 'form'

= link_to 'Show', @resume
'|
= link_to 'Back', resumes_path

app/views/resumes/index.html.slim
h1 Listing resumes

table
  tr
    th First name
    th Last name
    th
    th
    th
    th

  - @resumes.each do |resume|
    tr
      td = resume.first_name
      td = resume.last_name
      td = link_to resume_path(resume, :format => :pdf) do
        i.icon-eye-open
      td = link_to edit_resume_path(resume) do
        i.icon-edit
      td = link_to resume, :confirm => 'Are you sure?', :method => :delete do
        i.icon-trash

br

= link_to 'New Resume', new_resume_path

app/views/resumes/new.html.slim
h1 New resume

== render 'form'

= link_to 'Back', resumes_path

app/views/resumes/show.pdf.slim
doctype html
html
  head
    meta charset="utf-8"
    = wicked_pdf_stylesheet_link_tag "pdf"
  body
    h1
      = @resume.first_name
      strong
        = " #{@resume.last_name}"

    p
      = simple_format @resume.intro

    section.projects
      h2 Projets réalisés

      - @resume.projects.each do |project|
        section.project
          h3 = project.title
          p
            = simple_format project.description
          p
            span Durée :&nbsp;
            = project.duration
          p
            span Technologies :&nbsp;
            = project.technology_list

    section.experiences
      h2 Expérience professionnelle

      - @resume.experiences.map{|e|ExperienceDecorator.new(e)}.each do |experience|
        section.experience
          h3.title = experience.title
          h3.location = experience.location
          h3.timespan = experience.timespan
          - if experience.description.present?
            p
              = simple_format experience.description
          - if experience.technologies.any?
            p
              span Technologies :&nbsp;
              = experience.technology_list

